(require 'company-go)
(add-to-list 'company-backends 'company-go)
(add-hook 'go-mode-hook (lambda ()
			  (subword-mode)
			  (flycheck-mode)
			  (add-hook 'before-save-hook 'gofmt-before-save)
			  (if (not (string-match "go" compile-command))
			      (set (make-local-variable 'compile-command)
				   "go test -v && go build"))
			  (local-unset-key (kbd "M-."))
			  (local-set-key (kbd "M-.") 'godef-jump)))

(provide 'init-go)
