;; (add-hook 'go-mode-hook #'lsp-deferred)

(require 'company-go)
(add-hook 'go-mode-hook (lambda ()
			  (subword-mode)
			  (setq gofmt-command "goimports")
			  (add-hook 'before-save-hook 'gofmt-before-save)
			  (set (make-local-variable 'company-backends) '(company-go))
			  (if (not (string-match "go" compile-command))
			      (set (make-local-variable 'compile-command)
				   "go vet && go test -v"))
			  (local-unset-key (kbd "M-."))
			  ;; (local-set-key (kbd "M-.") 'lsp-find-definition)
			  (local-set-key (kbd "M-.") 'godef-jump)
			  (local-set-key (kbd "M-*") 'pop-tag-mark)
			  ))

(provide 'init-go)
